=== PanBrowse/PanVA/frontend/src/schema.config.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "ConfigMetadata": {
            "anyOf": [
                {
                    "$ref": "#/definitions/ConfigMetadataBoolean"
                },
                {
                    "$ref": "#/definitions/ConfigMetadataCategorical"
                },
                {
                    "$ref": "#/definitions/ConfigMetadataQuantitative"
                }
            ]
        },
        "ConfigMetadataBoolean": {
            "additionalProperties": false,
            "properties": {
                "column": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "labels": {
                    "additionalProperties": false,
                    "properties": {
                        "false": {
                            "type": "string"
                        },
                        "null": {
                            "type": "string"
                        },
                        "true": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "false",
                        "null",
                        "true"
                    ],
                    "type": "object"
                },
                "type": {
                    "enum": [
                        "boolean"
                    ],
                    "type": "string"
                },
                "values": {
                    "additionalProperties": false,
                    "properties": {
                        "false": {
                            "type": "string"
                        },
                        "true": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "false",
                        "true"
                    ],
                    "type": "object"
                }
            },
            "required": [
                "column",
                "label",
                "type"
            ],
            "type": "object"
        },
        "ConfigMetadataCategorical": {
            "additionalProperties": false,
            "properties": {
                "column": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "categorical"
                    ],
                    "type": "string"
                },
                "width": {
                    "type": "number"
                }
            },
            "required": [
                "column",
                "label",
                "type"
            ],
            "type": "object"
        },
        "ConfigMetadataQuantitative": {
            "additionalProperties": false,
            "properties": {
                "column": {
                    "type": "string"
                },
                "decimals": {
                    "type": "number"
                },
                "label": {
                    "type": "string"
                },
                "maxValue": {
                    "type": "number"
                },
                "suffix": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "quantitative"
                    ],
                    "type": "string"
                },
                "width": {
                    "type": "number"
                }
            },
            "required": [
                "column",
                "label",
                "type"
            ],
            "type": "object"
        }
    },
    "properties": {
        "apiUrl": {
            "type": "string"
        },
        "apps": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "homology": {
            "additionalProperties": false,
            "properties": {
                "alignmentMetadata": {
                    "items": {
                        "$ref": "#/definitions/ConfigMetadata"
                    },
                    "type": "array"
                },
                "annotations": {
                    "items": {
                        "additionalProperties": false,
                        "description": "Configuration.\n\nWhen making changes, be sure to update the config validator by running:\n  npm run generate-validators",
                        "properties": {
                            "column": {
                                "type": "string"
                            },
                            "label": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "column",
                            "label"
                        ],
                        "type": "object"
                    },
                    "type": "array"
                },
                "defaultId": {
                    "type": "string"
                },
                "defaultSequenceMetadataColumns": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "homologyMetadata": {
                    "items": {
                        "$ref": "#/definitions/ConfigMetadata"
                    },
                    "type": "array"
                },
                "sequenceMetadata": {
                    "items": {
                        "$ref": "#/definitions/ConfigMetadata"
                    },
                    "type": "array"
                },
                "trees": {
                    "items": {
                        "additionalProperties": false,
                        "properties": {
                            "filename": {
                                "type": "string"
                            },
                            "label": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "filename",
                            "label"
                        ],
                        "type": "object"
                    },
                    "type": "array"
                },
                "variableMetadata": {
                    "items": {
                        "$ref": "#/definitions/ConfigMetadata"
                    },
                    "type": "array"
                }
            },
            "type": "object"
        },
        "title": {
            "type": "string"
        }
    },
    "type": "object"
}

=== PanBrowse/PanVA/frontend/public/config copy.json
{
  "apiUrl": "http://localhost:5001/",
  "apps": [
    "homology",
    "genesets"
  ],
  "homology": {
    "alignmentMetadata": [
      {
        "type": "boolean",
        "column": "meta_boolean",
        "label": "Random boolean"
      },
      {
        "type": "categorical",
        "column": "meta_string",
        "label": "Random string"
      },
      {
        "type": "quantitative",
        "column": "meta_number",
        "label": "Random number"
      }
    ],
    "annotations": [
      {
        "column": "cds",
        "label": "CDS"
      },
      {
        "column": "exon",
        "label": "Exon"
      }
    ],
    "defaultId": "13803671",
    "defaultSequenceMetadataColumns": [
      "virulence",
      "species",
      "growth_rate",
      "strain_name"
    ],
    "homologyMetadata": [
      {
        "type": "quantitative",
        "column": "in_genomes",
        "label": "Found in genomes"
      },
      {
        "type": "categorical",
        "column": "gene_names",
        "label": "Gene names"
      },
      {
        "type": "categorical",
        "column": "classification",
        "label": "Classification"
      },
      {
        "type": "boolean",
        "column": "var_nucl_sites",
        "label": "Variable nucleotide sites"
      },
      {
        "type": "boolean",
        "column": "var_prot_sites",
        "label": "Variable protein sites"
      },
      {
        "type": "boolean",
        "column": "inf_nucl_sites",
        "label": "Informative nucleotide sites"
      },
      {
        "type": "boolean",
        "column": "inf_prot_sites",
        "label": "Informative protein sites"
      },
      {
        "type": "boolean",
        "column": "pheno_specific_nucl_changes",
        "label": "Phenotype specific nucleotide changes"
      },
      {
        "type": "boolean",
        "column": "pheno_specific_prot_changes",
        "label": "Phenotype specific protein changes"
      }
    ],
    "sequenceMetadata": [
      {
        "type": "boolean",
        "column": "virulence",
        "label": "Virulence",
        "values": {
          "true": "virulent",
          "false": "avirulent"
        },
        "labels": {
          "true": "Virulent",
          "false": "Avirulent",
          "null": "Unknown"
        }
      },
      {
        "type": "categorical",
        "column": "species",
        "label": "Species",
        "width": 80
      },
      {
        "type": "quantitative",
        "column": "growth_rate",
        "label": "Growth rate",
        "decimals": 1,
        "width": 100
      },
      {
        "type": "categorical",
        "column": "strain_name",
        "label": "Strain",
        "width": 120
      }
    ],
    "trees": [
      {
        "filename": "core_snp.txt",
        "label": "CoreSNP"
      },
      {
        "filename": "kmer.txt",
        "label": "K-Mer"
      }
    ],
    "variableMetadata": [
      {
        "type": "boolean",
        "column": "informative",
        "label": "Informative"
      },
      {
        "type": "boolean",
        "column": "pheno_specific",
        "label": "Phenotype specific"
      }
    ]
  },
  "title": "PanVA: Pectobacterium"
}
